# Set the C compiler
CC = gcc

# Set the C flags to be used by the compiler
CFLAGS = -g -Wall -Werror
IINC = -Iinclude

# List the source directories
SRC = src
PROJECTS = $(SERVER) $(CLIENT)

# Variables incase we need to change name
SERVER = server
CLIENT = client

# Set the directory to place the compiled binaries
BINDIR = bin

# Resources
RESOURCES_DIR = resources

# Make bin dir and copy files command
MAKE_BIN = $(shell mkdir -p $(BINDIR) && cp $(RESOURCES_DIR)/*.in $(BINDIR))
